### ISSUE TITLE
Background color on webpage is distracting

### ISSUE THREAD

**Issue by 2016rshah** [Bekt/invatar#4]
Currently, if you visit something like https://invatar0.appspot.com/svg/rs.jpg?s=100&bg=%23487A06&color=%23FFFFFF in your browser, the background of the page will take the same background color as the image. I personally think that is a bit distracting because you can not see where the image begins and ends, you just have to extrapolate what the square probably looks like. 

I think it would be better to have a white background or perhaps a background of the [image background color's inverse](http://www.mattlag.com/scripting/hexcolorinverter.php). What do you think? Is there some reason the page background should inherit the image's background color?

**Comment by Bekt** [comment]
Hey @2016rshah, thanks for bringing this up.

I do not like the way it is displayed either. Since the generated response is of of type `svg+xml` (as of right now), and not an actual image, it is up to the browser how to render this response. For example, Safari shows the background even [weirder](https://cloud.githubusercontent.com/assets/1221480/10286043/97dfa208-6b40-11e5-94a8-e332f71e9d68.png) (?!). 

I think this could be "fixed" by playing around with the `rect` shape; however, the response is meant to be used within HTML (e.g `img`, `background-url`), and not viewed directly in the browser or download it as an image. (for now)

**Comment by Bekt** [comment]
Closed by #5
